### ISSUE TITLE
Tabulator 4.0 is no longer jQuery dependent

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/MMM-Tabulator#10]
Good News from @olifolkerd (dev of Tabulator library)

> You will be happy to hear that as of version 4.0 Tabulator is no longer jQuery dependent and now comes with a tabulator_core.min.js without all the modules installed to make it even more light weight.

I've been away from developing for a few months, so I currently don't know if there is any side effects because of this. Please report, if you find any.

**Comment by Mark-papi** [comment]
tried to install it today and i got an error while i pm2 log mm

```
0|mm       |     at Function.Module._load (module.js:496:3)
0|mm       |     at Module.require (module.js:586:17)
0|mm       |     at require (internal/module.js:11:18)
0|mm       |     at loadModule (/home/pi/MagicMirror/js/app.js:127:17)
0|mm       | ReferenceError: NodeHelper is not defined
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tabulator/node_helper.js:30:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tabulator/node_helper.js:100:3)
0|mm       |     at Module._compile (module.js:642:30)
0|mm       |     at Object.Module._extensions..js (module.js:653:10)
0|mm       |     at Module.load (module.js:561:32)
0|mm       |     at tryModuleLoad (module.js:504:12)
0|mm       |     at Function.Module._load (module.js:496:3)
0|mm       |     at Module.require (module.js:586:17)
0|mm       |     at require (internal/module.js:11:18)
0|mm       |     at loadModule (/home/pi/MagicMirror/js/app.js:127:17)
```

**Comment by E3V3A** [comment]
Hi @Mark-papi 
Thanks for reporting. Not sure your issue is related to Tabulator as the error seem to be in `NodeHelper` while the following lines refer to line 100 which is not even present in my code. 

So please post a more complete beginning of your log and the exact commands you used to start with.
In addition the node and npm versions you're using. Also I have not used MM for quite some time, so in case the latest version has done some significant changes to the framework, I don't know about it.

**Comment by Mark-papi** [comment]
> In addition the node and npm versions you're using. Also I have not used MM for quite some time, so in case the latest version has done some significant changes to the framework, I don't know about it.

yea that may be, but i will also check what you said and i will reply.

**Comment by hellanerdy** [comment]
Its for sure broken. $(...).tabulator is not a function anymore. Check this out.
http://tabulator.info/docs/4.0/upgrade
https://github.com/olifolkerd/tabulator/issues/565
